### ISSUE TITLE
Enable property for TS4231 device in ConfigureHeadstage64 operator must be set to True by default

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1#322]
This would make sense and match the default settings for the Enable property of the ConfigureTSS4231V1 operator.

**Comment by jonnew** [comment]
This is the reason why and its a mistake as far as I can tell. Just delete:

https://github.com/open-ephys/bonsai-onix1/blob/450f82922b26917745f2e2a0a54803efb3d62fff/OpenEphys.Onix1/ConfigureHeadstage64.cs#L79

**Comment by jonnew** [comment]
Also, @self check for this in other headstages.
