### ISSUE TITLE
On miniscope, waiting for pll to settle might be causing instability

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/bonsai-onix1#327]
This is a purely empirical result done on a very limited set of devices.

However, I have noticed that when removing the waiting times on PLL activation, set on:
https://github.com/open-ephys/bonsai-onix1/blob/cd87fc45d58b87e92598ff037144c3f98a5befd2/OpenEphys.Onix1/ConfigureUclaMiniscopeV4Camera.cs#L222

register access to the atmega registers become much more reliable.

The old library did not include these waits, so they might be creating some unintended consequence.

**Comment by jonnew** [comment]
I would be happy to remove them, but of course, they were added for the same reason (in inverse) in the first place. It's possible both of these empirical tests are just spurious and we are looking at device to device variability. 

In that case they should be removed anyway.
