### ISSUE TITLE
Hardcode heartbeat enable property to true in ConfigureBreakoutBoard

### ISSUE THREAD

**Issue by jonnew** [open-ephys/bonsai-onix1#352]
This should be done by firmware as noted here:

https://github.com/open-ephys/onix-pcie-host-hdl/issues/4

However, we can at least get rid of this the enable field in `ConfigureHeartbeat` here:

https://github.com/open-ephys/bonsai-onix1/blob/18dd66bcf586edc00506209491035ecce7142739/OpenEphys.Onix1/ConfigureBreakoutBoard.cs#L31C61-L31C67

By using a similar strategy to the `AxisMap` properties of `ConfigureBno055`:

https://github.com/open-ephys/bonsai-onix1/blob/18dd66bcf586edc00506209491035ecce7142739/OpenEphys.Onix1/ConfigureNeuropixelsV2eHeadstage.cs#L51

**Comment by cjsha** [comment]
I think you mentioned that we don't need to be able to adjust BeatsPerSecond either. 

Considering this, it might be worth actually completely removing the HeartBeat properties from the ConfigureBreakoutBoard operator.
