### ISSUE TITLE
Make it easier to click to select/deselect channels in ChannelConfigurationDialog

### ISSUE THREAD

**Issue by bparks13** [open-ephys/bonsai-onix1#354]
Due to the current implementation of selecting and deselecting channels, there is overlapping functionality between just click, and click-and-drag. If the mouse moves even the smallest distance while clicking it will generate a click-and-drag event which then has a rectangle that is too small to select anything, and also precludes the user from deselecting since click-and-drag is only used to select channels.

One easy step: 
 - Check for the size of the selected rectangle, and if it is below a certain size then treat the event as a single click, which then gives back the power to deselect via a click event.

Other possible solutions: 
 - Add in a button that needs to be held to deselect (i.e., <kbd>Shift</kbd> + click), which can be for <kbd>Shift</kbd> + click-and-drag as well to bulk deselect channels

**Comment by bparks13** [comment]
Upon further testing, it appears that if there is more than one probe listed (such as in `Rhs2116ChannelConfigurationDialog`) the offset of the first probe is not taken into account when grabbing the index of the contact. This is an error, and should be corrected by applying the offset of all probes to the current index.

**Comment by jonnew** [comment]
I did some integration testing and everything feels very nice. Not extensive though.
