### ISSUE TITLE
Fix units in Rhs2116DataFrame xml comment

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1#355]
I'm guessing the mv needs to be µV. 

The offending lines:
https://github.com/open-ephys/bonsai-onix1/blob/634a54c3268c65215c734e8fbbb2dcf87215bee3/OpenEphys.Onix1/Rhs2116DataFrame.cs#L48
https://github.com/open-ephys/bonsai-onix1/blob/634a54c3268c65215c734e8fbbb2dcf87215bee3/OpenEphys.Onix1/Rhs2116DataFrame.cs#L34

I linked the second line as well because we use "uV" in the first instance and "µV" in the second instance.

This screenshot shows what I'm referring to. Look at the (micro-/milli-)Volt units.

![image](https://github.com/user-attachments/assets/1b09c1c3-bd7c-4d60-90d9-81ecb0e7426d)

**Comment by jonnew** [comment]
The only change that seems to be required is that in the DCData description, last sentence should be "To convert to millivolts"

Also, while we are at it, remove dashes between micro-volts and milli-volts.
