### ISSUE TITLE
Edit ConfigureHeadstageRhs2116 remarks

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1#357]
The first sentence for the ConfigureHeadstageRhs2116 remarks reads awkward to me:
> The Rhs2116 Headstage is a serialized headstage for small animals with 32 bi-directional channels which each can be used to deliver electrical stimuli.

Specifically, where we write "which each". I would write something like this:

> The Rhs2116 Headstage is a serialized headstage for small animals with 32 bi-directional channels that can be independently  configured to record electrophysiological signals or deliver electrical stimuli. 

Anyway, feel free to leave it if doesn't read awkward to you.

The relevant lines are here:
https://github.com/open-ephys/bonsai-onix1/blob/634a54c3268c65215c734e8fbbb2dcf87215bee3/OpenEphys.Onix1/ConfigureHeadstageRhs2116.cs#L11-L12

**Comment by jonnew** [comment]
Remove small animals as well.
