### ISSUE TITLE
Change "Configuration" label for aggregate operators in properties panel?

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1#360]
![image](https://github.com/user-attachments/assets/e6688a8a-dde8-4bde-89ee-71ce9d49821f)
To me, this "Configuration" label suggests that the `Name`, `Port` & `PortVoltage` properties are configuration properties. I'm not sure if this was intentional. "Aggregate" or "Hub" (though I think we are hiding that term from users) might be more correct labels? In any case, it happens to be true that all those properties are configuration properties, and I'm not sure there will ever be any acquisition properties that would fall into that section of the properties panel anyway. This is a nitpick.

**Comment by jonnew** [comment]
I think it's correct. These are configuration properties in the sense that they have no effect at runtime. In the same way that device level configuration properties don't.

**Comment by cjsha** [comment]
Sounds good
