### ISSUE TITLE
Consider unnlisting ConfigureHeartbeat operator  for searchable modules in Bonsai

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1#365]
Re: #352 I didn't consider how this affects the ConfigureHeatbeat operator. It seems that operator is still available if anyone wants to or modify the Enable or beatsPerSecond properties.

**Comment by jonnew** [comment]
You're overthinking things. The real solution is to modify the gateware for dev 0 so that it cannot be enabled. Having a generic configurable heartbeat is potentially useful.
