### ISSUE TITLE
ConfigurePolledBno055 does not configure the BNO055 in NDOF mode

### ISSUE THREAD

**Issue by jonnew** [open-ephys/bonsai-onix1#388]
This line configures the Bno055 in IMU mode

https://github.com/open-ephys/bonsai-onix1/blob/74f6f22d3df6ae18b9f7deccc57923cf5eaf2f13/OpenEphys.Onix1/ConfigurePolledBno055.cs#L122

This is almost certainly what is responsible for the large drift people are seeing with the neuropixels headstages. It should be 0x0C.

**Comment by cjsha** [comment]
I think the PR that closes this issue can also close https://github.com/open-ephys/bonsai-onix1/issues/378#issuecomment-2536239718
